-- Categorías base
INSERT INTO CATEGORIA (categoriaName, creationDate, creationUser) VALUES ('WRC', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO CATEGORIA (categoriaName, creationDate, creationUser) VALUES ('A', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO CATEGORIA (categoriaName, creationDate, creationUser) VALUES ('K', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO CATEGORIA (categoriaName, creationDate, creationUser) VALUES ('N', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');

-- Creamos un club
INSERT INTO CLUB (clubName,creationDate,creationUser) VALUES ('CLUB PRUEBA', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');

-- Creamos tres pilotos piloto
INSERT INTO PILOTO (pilotoName,creationDate,creationUser) VALUES ('PILOTO PRUEBA 1', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO PILOTO (pilotoName,creationDate,creationUser) VALUES ('PILOTO PRUEBA 2', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO PILOTO (pilotoName,creationDate,creationUser) VALUES ('PILOTO PRUEBA 3', CURRENT_TIMESTAMP, 'DATOS_PRUEBA');

-- Creamos una prueba 
INSERT INTO PRUEBA (ano, clubId, pruebaName,secciones, tramos,creationDate,creationUser) 
VALUES (YEAR(CURRENT_TIMESTAMP),(SELECT clubId FROM CLUB WHERE clubName = 'CLUB PRUEBA'),'PRUEBA PRUEBA', 6, 6, CURRENT_TIMESTAMP, 'DATOS_PRUEBA');

-- Creamos inscritos
INSERT INTO INSCRITO (pruebaId, pilotoId, categoriaId, creationDate, creationUser)
VALUES ((SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA'), (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1'), (SELECT categoriaId FROM CATEGORIA WHERE categoriaName = 'N'), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO INSCRITO (pruebaId, pilotoId, categoriaId, creationDate, creationUser)
VALUES ((SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA'), (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 2'), (SELECT categoriaId FROM CATEGORIA WHERE categoriaName = 'N'), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO INSCRITO (pruebaId, pilotoId, categoriaId, creationDate, creationUser)
VALUES ((SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA'), (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 3'), (SELECT categoriaId FROM CATEGORIA WHERE categoriaName = 'N'), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');

-- Creamos los tramos
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (1, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (2, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (3, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (4, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (5, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (5, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (7, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (8, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (9, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (10, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (11, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (12, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (13, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (14, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (15, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (16, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (17, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (18, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (19, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (20, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (21, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (22, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (23, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (24, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (25, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (26, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (27, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (28, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (29, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (30, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (31, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (32, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (33, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (34, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (35, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');
INSERT INTO TRAMO (tramoPruebaId, inscritoId, creationDate, creationUser) VALUES (36, (SELECT inscritoId FROM INSCRITO WHERE pruebaId = (SELECT pruebaId FROM PRUEBA WHERE pruebaName = 'PRUEBA PRUEBA') AND pilotoId = (SELECT pilotoId FROM PILOTO WHERE pilotoName = 'PILOTO PRUEBA 1')), CURRENT_TIMESTAMP, 'DATOS_PRUEBA');